#!/bin/bash
# =============================================================================
# deploy.sh - Dynamic Templating Engine for Enterprise SaaS Kit
# =============================================================================
# Parses saas-init.yml to export environment variables, generates a .env file
# for docker-compose, and processes all .template files under infrastructure/.
#
# Usage: ./deploy.sh
#
# Prerequisites:
#   - yq (https://github.com/mikefarah/yq) - install with: brew install yq
#   - envsubst (from gettext, pre-installed on most systems)
# =============================================================================

set -euo pipefail

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
CONFIG_FILE="saas-init.yml"
ENV_OUTPUT_FILE=".env"
SEARCH_DIRS=("infrastructure")

# -----------------------------------------------------------------------------
# Dependency Checks
# -----------------------------------------------------------------------------
command -v yq >/dev/null 2>&1 || {
  echo "ERROR: 'yq' is not installed. Install it with: brew install yq" >&2
  exit 1
}

command -v envsubst >/dev/null 2>&1 || {
  echo "ERROR: 'envsubst' is not installed. Install gettext: brew install gettext" >&2
  exit 1
}

command -v jq >/dev/null 2>&1 || {
  echo "ERROR: 'jq' is not installed. Install it with: brew install jq" >&2
  exit 1
}

# -----------------------------------------------------------------------------
# Verify config file exists
# -----------------------------------------------------------------------------
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "ERROR: Configuration file '$CONFIG_FILE' not found." >&2
  echo "Copy saas-init.yml.example to saas-init.yml and edit it." >&2
  exit 1
fi

# -----------------------------------------------------------------------------
# Parse saas-init.yml and generate .env file
# -----------------------------------------------------------------------------
echo ">> Parsing configuration from $CONFIG_FILE ..."

# Start fresh .env file
echo "# Auto-generated by deploy.sh from $CONFIG_FILE - DO NOT EDIT" > "$ENV_OUTPUT_FILE"
echo "# Re-run ./deploy.sh to regenerate" >> "$ENV_OUTPUT_FILE"
echo "" >> "$ENV_OUTPUT_FILE"

# Get all paths, save to temp file
PATHS_FILE=$(mktemp)
yq eval '.. | path | join(".")' "$CONFIG_FILE" > "$PATHS_FILE" 2>/dev/null

while IFS= read -r path; do
  [ -z "$path" ] && continue

  dot_path=".$path"

  # Skip non-scalar nodes
  tag=$(yq eval "$dot_path | tag" "$CONFIG_FILE" 2>/dev/null)
  if [[ "$tag" != "!!str" && "$tag" != "!!int" && "$tag" != "!!float" && "$tag" != "!!bool" ]]; then
    continue
  fi

  value=$(yq eval "$dot_path" "$CONFIG_FILE" 2>/dev/null)

  # Convert path to env var name
  env_name=$(echo "$path" | awk -F. '{for(i=1;i<=NF;i++) printf "%s_", tolower($i)}' | sed 's/_$//')
  env_name=$(echo "$env_name" | tr '-' '_' | tr '[:lower:]' '[:upper:]')

  echo "${env_name}=${value}" >> "$ENV_OUTPUT_FILE"
  export "${env_name}=${value}"
done < "$PATHS_FILE"

rm -f "$PATHS_FILE"
echo "   Generated: $ENV_OUTPUT_FILE"

# -----------------------------------------------------------------------------
# Generate Client Secret if empty
# -----------------------------------------------------------------------------
if [[ -z "${ARCHCORE_CLIENT_SECRET:-}" ]]; then
  ARCHCORE_CLIENT_SECRET=$(openssl rand -hex 32)
  # Remove empty entry if exists, then add new one
  sed -i.bak '/^ARCHCORE_CLIENT_SECRET=$/d' "$ENV_OUTPUT_FILE" 2>/dev/null || true
  echo "ARCHCORE_CLIENT_SECRET=${ARCHCORE_CLIENT_SECRET}" >> "$ENV_OUTPUT_FILE"
  export ARCHCORE_CLIENT_SECRET="${ARCHCORE_CLIENT_SECRET}"
  echo "   Generated: ARCHCORE_CLIENT_SECRET (auto-generated)"
else
  echo "   Using existing: ARCHCORE_CLIENT_SECRET"
fi

# -----------------------------------------------------------------------------
# Dynamic Template Discovery and Processing
# -----------------------------------------------------------------------------
GENERATED_COUNT=0

for search_dir in "${SEARCH_DIRS[@]}"; do
  if [[ ! -d "$search_dir" ]]; then
    echo "WARN: Directory '$search_dir' not found, skipping." >&2
    continue
  fi

  # Use temp file for find results
  TEMPLATES_FILE=$(mktemp)
  find "$search_dir" -name "*.template" -type f > "$TEMPLATES_FILE"

  while IFS= read -r template_file; do
    output_file="${template_file%.template}"
    envsubst < "$template_file" > "$output_file"

    # Post-process Keycloak realm JSON files for feature flags
    if [[ "$output_file" == *realm*.json ]]; then
      # Apply forgot password feature flag
      if [[ "${FEATURES_FORGOTPASSWORD_ENABLED:-true}" == "false" ]]; then
        jq '.resetPasswordAllowed = false' "$output_file" > "${output_file}.tmp" && mv "${output_file}.tmp" "$output_file"
        echo "     -> Forgot password: DISABLED"
      else
        echo "     -> Forgot password: ENABLED"
      fi

      # Apply google login feature flag
      if [[ "${FEATURES_GOOGLELOGIN_ENABLED:-true}" == "false" ]]; then
        jq 'del(.identityProviders) | del(.identityProviderMappers)' "$output_file" > "${output_file}.tmp" && mv "${output_file}.tmp" "$output_file"
        echo "     -> Google login: DISABLED"
      else
        echo "     -> Google login: ENABLED"
      fi

      # Apply smtp feature flag
      if [[ "${FEATURES_SMTP_ENABLED:-true}" == "false" ]]; then
        jq '.smtpServer = {}' "$output_file" > "${output_file}.tmp" && mv "${output_file}.tmp" "$output_file"
        echo "     -> SMTP: DISABLED"
      else
        echo "     -> SMTP: ENABLED"
      fi
    fi

    echo "   Generated: $output_file"
    GENERATED_COUNT=$((GENERATED_COUNT + 1))
  done < "$TEMPLATES_FILE"

  rm -f "$TEMPLATES_FILE"
done

# -----------------------------------------------------------------------------
# Generate docker-compose.yml dynamically based on feature flags
# -----------------------------------------------------------------------------
echo ">> Generating docker-compose.yml with feature flags..."

DOCKER_COMPOSE_FILE="docker-compose.yml"

# Start building the environment section
ENV_SECTION=""

# Core Keycloak env vars (always included)
ENV_SECTION="${ENV_SECTION}      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/\${DB_NAME}
      KC_DB_USERNAME: \${DB_USER}
      KC_DB_PASSWORD: \${DB_PASSWORD}
      KC_HOSTNAME_STRICT: \"false\"
      KC_HTTP_HOST: \"0.0.0.0\"
      KC_PORT: 8080
      KC_HTTP_PORT: 8080
      KC_HEALTH_ENABLED: \"true\"
      KC_BOOTSTRAP_ADMIN_USERNAME: \${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: \${KEYCLOAK_ADMIN_PASS}
"

# Frontend URL (always included)
ENV_SECTION="${ENV_SECTION}      # Frontend URL for client configuration
      FRONTEND_URL: \${FRONTEND_URL}
"

# JWE SPI config (always included)
ENV_SECTION="${ENV_SECTION}      # Keycloak provider config properties (passed via env for SPI)
      archcore.jwe.default-jwks-url: \${ARCHCORE_JWE_DEFAULT_JWKS_URL}
      archcore.jwe.cache-ttl-ms: \${ARCHCORE_JWE_CACHE_TTL_MS}
      archcore.jwe.algorithm: \${ARCHCORE_JWE_ALGORITHM}
      archcore.jwe.encryption-method: \${ARCHCORE_JWE_ENCRYPTION_METHOD}
      archcore.jwe.key-id: \${ARCHCORE_JWE_KEY_ID}
"

# Client Secret (for realm template)
ENV_SECTION="${ENV_SECTION}      # Client Secret for archcore-client
      ARCHCORE_CLIENT_SECRET: \${ARCHCORE_CLIENT_SECRET}
"

# SMTP (conditional)
if [[ "${FEATURES_SMTP_ENABLED:-true}" == "true" ]]; then
  ENV_SECTION="${ENV_SECTION}      # SMTP Configuration for Forgot Password emails
      KEYCLOAK_SMTP_HOST: \${KEYCLOAK_SMTP_HOST}
      KEYCLOAK_SMTP_PORT: \${KEYCLOAK_SMTP_PORT}
      KEYCLOAK_SMTP_USER: \${KEYCLOAK_SMTP_USER}
      KEYCLOAK_SMTP_PASSWORD: \${KEYCLOAK_SMTP_PASSWORD}
      KEYCLOAK_SMTP_FROM: \${KEYCLOAK_SMTP_FROM}
"
fi

# Google Login (conditional)
if [[ "${FEATURES_GOOGLELOGIN_ENABLED:-true}" == "true" ]]; then
  ENV_SECTION="${ENV_SECTION}      # Google Social Login
      KEYCLOAK_GOOGLE_CLIENTID: \${KEYCLOAK_GOOGLE_CLIENTID}
      KEYCLOAK_GOOGLE_CLIENTSECRET: \${KEYCLOAK_GOOGLE_CLIENTSECRET}
"
fi

# Generate the complete docker-compose.yml
cat > "$DOCKER_COMPOSE_FILE" << EOF
version: "3.8"

services:
  postgres:
    image: postgres:18-alpine
    container_name: \${PROJECT_NAME}-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: \${DB_NAME}
      POSTGRES_USER: \${DB_USER}
      POSTGRES_PASSWORD: \${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${DB_USER} -d \${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    build:
      context: .
      dockerfile: infrastructure/keycloak/Dockerfile
    container_name: \${PROJECT_NAME}-keycloak
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
${ENV_SECTION}    ports:
      - "8080:8080"
    volumes:
      - ./infrastructure/keycloak/templates:/opt/keycloak/data/import:ro
      - keycloak_data:/opt/keycloak/data
    command: ["start-dev", "--import-realm"]

volumes:
  postgres_data:
  keycloak_data:
EOF

echo "   Generated: $DOCKER_COMPOSE_FILE"
echo "     -> SMTP env vars: $(if [[ "${FEATURES_SMTP_ENABLED:-true}" == "true" ]]; then echo "INCLUDED"; else echo "EXCLUDED"; fi)"
echo "     -> Google env vars: $(if [[ "${FEATURES_GOOGLELOGIN_ENABLED:-true}" == "true" ]]; then echo "INCLUDED"; else echo "EXCLUDED"; fi)"

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------
echo ""
echo ">> Deployment configuration generated successfully."
echo "   .env file: $ENV_OUTPUT_FILE"
echo "   Templates processed: $GENERATED_COUNT"
echo ""
echo "   Next steps:"
echo "     docker compose up -d"
