#!/bin/bash
# =============================================================================
# deploy.sh - Dynamic Templating Engine for Enterprise SaaS Kit
# =============================================================================
# Parses saas-init.yml to export environment variables, generates a .env file
# for docker-compose, and processes all .template files under infrastructure/.
#
# Usage: ./deploy.sh
#
# Prerequisites:
#   - yq (https://github.com/mikefarah/yq) - install with: brew install yq
#   - envsubst (from gettext, pre-installed on most systems)
# =============================================================================

set -euo pipefail

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
CONFIG_FILE="saas-init.yml"
ENV_OUTPUT_FILE=".env"
SEARCH_DIRS=("infrastructure")

# -----------------------------------------------------------------------------
# Dependency Checks
# -----------------------------------------------------------------------------
command -v yq >/dev/null 2>&1 || {
  echo "ERROR: 'yq' is not installed. Install it with: brew install yq" >&2
  exit 1
}

command -v envsubst >/dev/null 2>&1 || {
  echo "ERROR: 'envsubst' is not installed. Install gettext: brew install gettext" >&2
  exit 1
}

# -----------------------------------------------------------------------------
# Verify config file exists
# -----------------------------------------------------------------------------
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "ERROR: Configuration file '$CONFIG_FILE' not found." >&2
  echo "Copy saas-init.yml.example to saas-init.yml and edit it." >&2
  exit 1
fi

# -----------------------------------------------------------------------------
# Parse saas-init.yml and generate .env file
# -----------------------------------------------------------------------------
echo ">> Parsing configuration from $CONFIG_FILE ..."

# Start fresh .env file
echo "# Auto-generated by deploy.sh from $CONFIG_FILE - DO NOT EDIT" > "$ENV_OUTPUT_FILE"
echo "# Re-run ./deploy.sh to regenerate" >> "$ENV_OUTPUT_FILE"
echo "" >> "$ENV_OUTPUT_FILE"

# Get all paths, save to temp file
PATHS_FILE=$(mktemp)
yq eval '.. | path | join(".")' "$CONFIG_FILE" > "$PATHS_FILE" 2>/dev/null

while IFS= read -r path; do
  [ -z "$path" ] && continue

  dot_path=".$path"

  # Skip non-scalar nodes
  tag=$(yq eval "$dot_path | tag" "$CONFIG_FILE" 2>/dev/null)
  if [[ "$tag" != "!!str" && "$tag" != "!!int" && "$tag" != "!!float" && "$tag" != "!!bool" ]]; then
    continue
  fi

  value=$(yq eval "$dot_path" "$CONFIG_FILE" 2>/dev/null)

  # Convert path to env var name
  env_name=$(echo "$path" | awk -F. '{for(i=1;i<=NF;i++) printf "%s_", tolower($i)}' | sed 's/_$//')
  env_name=$(echo "$env_name" | tr '-' '_' | tr '[:lower:]' '[:upper:]')

  echo "${env_name}=${value}" >> "$ENV_OUTPUT_FILE"
  export "${env_name}=${value}"
done < "$PATHS_FILE"

rm -f "$PATHS_FILE"
echo "   Generated: $ENV_OUTPUT_FILE"

# -----------------------------------------------------------------------------
# Dynamic Template Discovery and Processing
# -----------------------------------------------------------------------------
GENERATED_COUNT=0

for search_dir in "${SEARCH_DIRS[@]}"; do
  if [[ ! -d "$search_dir" ]]; then
    echo "WARN: Directory '$search_dir' not found, skipping." >&2
    continue
  fi

  # Use temp file for find results
  TEMPLATES_FILE=$(mktemp)
  find "$search_dir" -name "*.template" -type f > "$TEMPLATES_FILE"

  while IFS= read -r template_file; do
    output_file="${template_file%.template}"
    envsubst < "$template_file" > "$output_file"
    echo "   Generated: $output_file"
    GENERATED_COUNT=$((GENERATED_COUNT + 1))
  done < "$TEMPLATES_FILE"

  rm -f "$TEMPLATES_FILE"
done

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------
echo ""
echo ">> Deployment configuration generated successfully."
echo "   .env file: $ENV_OUTPUT_FILE"
echo "   Templates processed: $GENERATED_COUNT"
echo ""
echo "   Next steps:"
echo "     docker compose up -d"
