spring:
  config:
    activate:
      on-profile: prod

spring.security.oauth2.resourceserver.jwt.issuer-uri: ${KEYCLOAK_ISSUER_URI}

archcore:
  security:
    jwe:
      private-key-location: ${JWE_PRIVATE_KEY_PATH}
      public-key-location: ${JWE_PUBLIC_KEY_PATH}
